name: Postman CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: npm install -g @postman/cli

      - name: Run collection
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          postman collection run "52238111-b8c1f81c-2bb7-460d-b56d-4df857eb5bf1" \
            -e "52238111-310fba8f-85e9-4e9d-8e37-8cfa71f59680" \
            --report-events \
            --api-key "$POSTMAN_API_KEY"